version: "3.3"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - INTERNAL_SUBNET=10.13.13.0 #optional
    ports:
      - 5800:5800
    volumes:
      - /volume1/media/nas-compose/vpn/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  jdownloader:
    image: jaymoulin/jdownloader:2.1.3
    container_name: jdownloader
    user: 0:0
    depends_on:
      - wireguard
    volumes:
      - /volume1/media/Downloads:/opt/JDownloader/Downloads
      - /volume1/media/nas-compose/vpn/config:/opt/JDownloader/app/cfg
      - /volume1/media/nas-compose/vpn/jdlogs:/opt/JDownloader/app/logs
      - /volume1/media/nas-compose/vpn/extensions:/opt/JDownloader/app/extensions 
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYJD_USER=s1588419@gmail.com
      - MYJD_PASSWORD=night17293
      - MYJD_DEVICE_NAME=unas
    network_mode: "service:wireguard"
    restart: unless-stopped
