version: "3.3"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    networks:
      - vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules:ro
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    depends_on:
      - wireguard
    volumes:
      - ./config:/opt/JDownloader/cfg
      - /srv/dev-disk-by-label-media/Downloads:/opt/JDownloader/Downloads
    env_file:
      - .env
    network_mode: "service:wireguard"
    restart: unless-stopped

networks:
  vpn:
    driver: bridge