version: "3.3"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - INTERNAL_SUBNET=10.13.13.0 #optional
    ports:
      - 51820:51820/udp
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  proxy:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8007:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000

  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    user: 1000:100
    depends_on:
      - wireguard
    volumes:
      - ./config:/opt/JDownloader/cfg
      - /srv/dev-disk-by-label-media/media/Downloads:/opt/JDownloader/Downloads
    env_file:
      - .env
    network_mode: "service:wireguard"
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USER=admin
      - PASS=admin
    network_mode: "service:wireguard"
    volumes:
      - ./transmission/config:/config
      - ./watch:/watch
      - /srv/dev-disk-by-label-media/media/DownloadsTransmission:/downloads
    restart: unless-stopped
