version: '3.3'
services:
    plex:
        image: plexinc/pms-docker
        container_name: plex
        restart: unless-stopped
        ports:
            - 32400:32400/tcp
        environment:
            - TZ=Europe/Berlin
            - PLEX_CLAIM=${PLEX_CLAIM:-"claim-L-S_syn_daaaaaaaaaaaaaa"}
        volumes:
            - ./config:/config
            - ./transcode:/transcode
            - /srv/dev-disk-by-label-media/media:/data
        devices:
            - /dev/dri:/dev/dri

