version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - n8n_net
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: n8n_password
      N8N_ENCRYPTION_KEY: v23t5mu90wiovyt909070v512700usdnjklasdfuyiogeui9bsduyag
      GENERIC_TIMEZONE: "Europe/Berlin"
      TZ: "Europe/Berlin"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./files:/files
    depends_on:
      - postgres
    networks:
      - n8n_net
    restart: unless-stopped

networks:
  n8n_net:

volumes:
  n8n_storage:
