version: '2.1'

services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - ./data:/root
