services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./config:/config # replace host path or volume as needed
    ports:
      - 8016:1337
    restart: unless-stopped
