# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.
version: "3.4"

services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    user: 0:0
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
      - mail
    ports:
      - 8008:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./paperless:/usr/src/paperless/data
      - /srv/dev-disk-by-label-media/media/Documents/media:/usr/src/paperless/media:rshared
      - /srv/dev-disk-by-label-media/media/Documents/consume:/usr/src/paperless/consume:rshared
      - /srv/dev-disk-by-label-media/media/Documents/export:/usr/src/paperless/export:rshared
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_FILENAME_FORMAT: "{created_year}-{created_month}-{created_day}-{title}-{correspondent}"
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_ENABLE_UPDATE_CHECK: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1

  tika:
    image: apache/tika
    restart: unless-stopped

  mail:
    image: shenxn/protonmail-bridge:latest
    container_name: mail
    restart: unless-stopped
    volumes:
      - ./data/protonmail:/root

#  rclone:
#    image: rclone/rclone
#    container_name: rclone
#    restart: unless-stopped
#    user: 0:0
#    cap_add:
#      - SYS_ADMIN
#    security_opt:
#      - apparmor:unconfined
#    volumes:
#      - ~/.config/rclone:/config/rclone
#      - /srv/paperless:/data:rshared
#      - /etc/passwd:/etc/passwd:ro
#      - /etc/group:/etc/group:ro
#    environment:
#      - PUID=0
#      - PGID=0
#    devices:
#      - /dev/fuse
#    command: "mount onedrive:Documents/paperless /data/documents --allow-non-empty --vfs-cache-mode full"
#    command: "mount gd-tv:   /data/gd-tv    --allow-other --transfers 1 --dir-cache-time 1000h --buffer-size 8M --log-file /data/logs/tv.log --log-level DEBUG"
