---
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - music:/music
      - ./ingest:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped

volumes:
    music:
      driver: local
      driver_opts:
        type: cifs
        device: //192.168.1.100/media/Music
        o: username=marcel,password=Night17293
