version: "3.5"
services:
  diun:
    image: crazymax/diun:latest
    command: serve
    container_name: diun
    volumes:
      - ./data:/data
      - ./diun.yml:/etc/diun/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: unless-stopped
