version: "3"
services:
  ouroboros:
    image: pyouroboros/ouroboros
    container_name: ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=jellyfin portainer
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
