services:
    ollama:
        container_name: ollama
        image: ollama/ollama:rocm
        devices:
            - /dev/kfd
            - /dev/dri
        volumes:
            - ./ollama:/root/.ollama
        ports:
            - 11434:11434
        restart: unless-stopped
