version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./transtmp:/transtmp
      - /srv/dev-disk-by-label-media/media/Anime:/media/Anime
      - /srv/dev-disk-by-label-media/media/Animation:/media/Animation
      - /srv/dev-disk-by-label-media/media/Movies:/media/Movies
      - /srv/dev-disk-by-label-media/media/Series:/media/Series
    ports:
      - 8001:8096
      #- 4431:8920
      - 7359:7359/udp
      - 1900:1900/udp
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
