version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /srv/dev-disk-by-label-media/Anime:/media/Anime
      - /srv/dev-disk-by-label-media/Movies:/media/Movies
      - /srv/dev-disk-by-label-media/Series:/media/Series
    ports:
      - 8001:8096
      #- 4431:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped