version: '3.3'
services:
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
          - 8002:8000
          - 9000:9000
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./config:/data
