version: '3.3'
services:
    netdata:
        image: netdata/netdata
        container_name: netdata
        hostname: netdata.locale.net
        ports:
            - 19999:19999
        volumes:
            # folder ./lib needs to be writeable for anyone
            - ./lib:/var/lib/netdata
            # folder ./cache needs to be writeable for anyone
            - ./cache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor=unconfined
