version: "3"
services:
  balancer:
    container_name: balancer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:/config
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
